palabra = input ("Introduce una palabra: ")
numero_entero = int (input("Introduce un número sin decimales: "))
numero_flotante = float (input("Introduce un número con decimales: "))
numero_complejo = complex (input ("Intoduce un número complejo: "))
print ()
print ("str: ",palabra)
print ("int: ",numero_entero)
print ("float: ",numero_flotante)
print ("complex: ", numero_complejo)
print ()
print ()
print ()
print ()
nombre = input ("Escribe tu nombre: ")
print ("Hola,",nombre,"vamos a realizar una suma.")
numero1 = int (input("Por favor, introduce el primer valor: "))
numero2 = int (input("Por favor, introduce el segundo valor: "))
resultado = numero1+numero2
print (nombre+",","el resultado de la suma es: ",resultado)
